image: alpine

before_script:
- apk update
- apk add doxygen
- apk add ttf-freefont graphviz

pages:
  script:
  - doxygen
  artifacts:
    paths:
    - public
  only:
  - master

build:
        script:
        - mkdir cmake-build-debug
        - cd cmake-build-debug
        - cmake ..
        - make
